AWSTemplateFormatVersion: '2010-09-09'
Description: 'Container-based Lambda functions for multi-tenant log distribution'

Parameters:
  Environment:
    Type: String
    Default: development
    AllowedValues: [production, staging, development]
    Description: Environment name
    
  ProjectName:
    Type: String
    Default: multi-tenant-logging
    Description: Name of the project for resource naming
    
  LogDistributorRoleArn:
    Type: String
    Description: ARN of the log distributor Lambda IAM role
    
  TenantConfigTableName:
    Type: String
    Description: Name of the tenant configuration DynamoDB table
    
  SQSQueueArn:
    Type: String
    Description: ARN of the SQS queue to process messages from
    
  ECRImageUri:
    Type: String
    Description: URI of the ECR container image for the log processor
    
  CentralLogDistributionRoleArn:
    Type: String
    Description: ARN of the central log distribution role for cross-account access

Resources:

  # CloudWatch Log Group for Lambda functions
  LogDistributorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${Environment}-log-distributor'
      RetentionInDays: 14
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: cloudformation
        - Key: StackType
          Value: lambda-functions

  # Container-based Lambda function for log distribution
  LogDistributorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-log-distributor'
      PackageType: Image
      Code:
        ImageUri: !Ref ECRImageUri
      Role: !Ref LogDistributorRoleArn
      Environment:
        Variables:
          TENANT_CONFIG_TABLE: !Ref TenantConfigTableName
          MAX_BATCH_SIZE: "1000"
          RETRY_ATTEMPTS: "3"
          CENTRAL_LOG_DISTRIBUTION_ROLE_ARN: !Ref CentralLogDistributionRoleArn
          EXECUTION_MODE: "lambda"
          AWS_REGION: !Ref AWS::Region
      Timeout: 300
      MemorySize: 1024
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-log-distributor'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: cloudformation
        - Key: StackType
          Value: lambda-functions

  # Event Source Mapping for SQS to Lambda
  LogDeliveryEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !Ref SQSQueueArn
      FunctionName: !Ref LogDistributorFunction
      BatchSize: 10
      MaximumBatchingWindowInSeconds: 5


Outputs:
  LogDistributorFunctionName:
    Description: Name of the log distributor Lambda function
    Value: !Ref LogDistributorFunction
    Export:
      Name: !Sub '${AWS::StackName}-LogDistributorFunctionName'

  LogDistributorFunctionArn:
    Description: ARN of the log distributor Lambda function
    Value: !GetAtt LogDistributorFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LogDistributorFunctionArn'