apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vector-logs
  labels:
    app.kubernetes.io/name: vector
    app.kubernetes.io/part-of: multi-tenant-logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vector-logs
subjects:
- kind: ServiceAccount
  name: vector-logs
  namespace: logging