apiVersion: v1
kind: ConfigMap
metadata:
  name: log-processor-config
  namespace: logging
  labels:
    app.kubernetes.io/name: log-processor
    app.kubernetes.io/part-of: multi-tenant-logging
data:
  # Execution mode for the processor
  EXECUTION_MODE: "sqs"
  
  # AWS Region
  AWS_REGION: "us-east-2"
  
  # Processing configuration
  MAX_BATCH_SIZE: "1000"
  RETRY_ATTEMPTS: "3"
  
  # Logging configuration
  LOG_LEVEL: "INFO"