apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: log-processor
  labels:
    app.kubernetes.io/name: log-processor
    app.kubernetes.io/part-of: multi-tenant-logging
rules:
# Pod status monitoring for health checks
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
# ConfigMap access for dynamic configuration
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Event creation for audit trail
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]